Some weights of SegformerForSemanticSegmentation were not initialized from the model checkpoint at nvidia/mit-b0 and are newly initialized: ['decode_head.linear_c.2.proj.weight', 'decode_head.linear_c.1.proj.bias', 'decode_head.linear_fuse.weight', 'decode_head.linear_c.3.proj.bias', 'decode_head.batch_norm.bias', 'decode_head.linear_c.0.proj.bias', 'decode_head.linear_c.1.proj.weight', 'decode_head.linear_c.0.proj.weight', 'decode_head.linear_c.3.proj.weight', 'decode_head.linear_c.2.proj.bias', 'decode_head.batch_norm.running_var', 'decode_head.batch_norm.num_batches_tracked', 'decode_head.batch_norm.weight', 'decode_head.classifier.weight', 'decode_head.classifier.bias', 'decode_head.batch_norm.running_mean']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
  0%|                                                                                                                            | 0/198 [00:00<?, ?it/s]Traceback (most recent call last):
  File "C:\Users\chris\OneDrive\Documents\GitHub\thermographic_inspection\models\Segformer\train.py", line 95, in <module>
    trainer.train()
  File "C:\Users\chris\anaconda3\envs\Research\Lib\site-packages\transformers\trainer.py", line 1553, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\anaconda3\envs\Research\Lib\site-packages\transformers\trainer.py", line 1813, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "C:\Users\chris\anaconda3\envs\Research\Lib\site-packages\accelerate\data_loader.py", line 384, in __iter__
    current_batch = next(dataloader_iter)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\anaconda3\envs\Research\Lib\site-packages\torch\utils\data\dataloader.py", line 633, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\anaconda3\envs\Research\Lib\site-packages\torch\utils\data\dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\anaconda3\envs\Research\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = self.dataset.__getitems__(possibly_batched_index)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\anaconda3\envs\Research\Lib\site-packages\datasets\arrow_dataset.py", line 2807, in __getitems__
    batch = self.__getitem__(keys)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\anaconda3\envs\Research\Lib\site-packages\datasets\arrow_dataset.py", line 2803, in __getitem__
    return self._getitem(key)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\anaconda3\envs\Research\Lib\site-packages\datasets\arrow_dataset.py", line 2788, in _getitem
    formatted_output = format_table(
                       ^^^^^^^^^^^^^
  File "C:\Users\chris\anaconda3\envs\Research\Lib\site-packages\datasets\formatting\formatting.py", line 629, in format_table
    return formatter(pa_table, query_type=query_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\anaconda3\envs\Research\Lib\site-packages\datasets\formatting\formatting.py", line 400, in __call__
    return self.format_batch(pa_table)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\anaconda3\envs\Research\Lib\site-packages\datasets\formatting\formatting.py", line 515, in format_batch
    return self.transform(batch)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\OneDrive\Documents\GitHub\thermographic_inspection\models\Segformer\utils.py", line 58, in __call__
    for image, mask in zip(batch["image"], batch["label"]):
                                           ~~~~~^^^^^^^^^
KeyError: 'label'